# Generated by Django 5.0.6 on 2024-06-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_remove_user_req_req_mes_remove_user_req_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_req',
            name='sharing_type',
            field=models.CharField(default=1, max_length=5),
        ),
    ]
